#!/bin/sh
if [ $# -ne 2 ]; then
  echo "Usage: $0 -s <number_of_repeats> <delay_in_seconds>"
  exit 1
fi

# Check if the first argument is a number
if ! [[ $1 =~ ^[0-9]+$ ]]; then
  echo "Error: The first argument is not a valid number."
  exit 1
fi

# Check if the second argument is a number
if ! [[ $2 =~ ^[0-9]+$ ]]; then
  echo "Error: The second argument is not a valid number."
  exit 1
fi

osascript -e "repeat $1 times" -e 'tell application "Finder" to make new Finder window' -e 'end repeat' -e "delay $2" -e 'tell application "Finder" to close Finder windows'